import type { Address } from "viem";
import canonicalAddresses from "@/generated/addresses.json";
import chainConstants from "@/generated/chainConstants.json";

/**
 * Vendored copy of the federation-canonical contract-address table for
 * chain 40204. Source-of-truth lives at
 * `citrate-chain/contracts/addresses/40204.json` and is regenerated by
 * `citrate-chain/scripts/ops/emit-address-table.sh` after every
 * post-redeploy ceremony. Sync via `pnpm sync-addresses` (see
 * `scripts/sync-addresses.mjs`). Never hardcode a contract address inline;
 * read it from {@link CITRATE_ADDRESSES} or {@link CONTRACT_ADDRESSES}.
 */

const ADDRESS_RE = /^0x[0-9a-fA-F]{40}$/;

/** An env override only when set to a well-formed address; otherwise the vendored book wins. */
function bookUnlessOverridden(override: string | undefined, fromBook: string): Address {
  return (override && ADDRESS_RE.test(override) ? override : fromBook) as Address;
}

/**
 * Well-known on-chain addresses CitrateScan decodes by default, from the vendored
 * book. `NEXT_PUBLIC_MODEL_REGISTRY` / `NEXT_PUBLIC_INFERENCE_ROUTER` override
 * them only when set to a well-formed address (a preview or staging deploy);
 * leave them unset in production so a chain re-roll needs no env change.
 * Always confirm with `eth_getCode` before treating an address as a contract
 * (Rule 11).
 */
export const CITRATE_ADDRESSES = {
  /** AI ModelRegistry — see canonical contracts.ModelRegistry. */
  modelRegistry: bookUnlessOverridden(process.env.NEXT_PUBLIC_MODEL_REGISTRY, canonicalAddresses.contracts.ModelRegistry),
  /** InferenceRouter — see canonical contracts.InferenceRouter. */
  inferenceRouter: bookUnlessOverridden(process.env.NEXT_PUBLIC_INFERENCE_ROUTER, canonicalAddresses.contracts.InferenceRouter),
} as const;

/** The full contract map from the canonical table (for callers that need more
 * than the two top-of-mind ones above). Address is lowercased. */
export const CONTRACT_ADDRESSES = canonicalAddresses.contracts as Readonly<
  Record<string, Address>
>;

/** The ERC-4337 v0.7 AA stack from the canonical table. */
export const AA_STACK = canonicalAddresses.aaStack as Readonly<
  Record<string, Address>
>;

/** Deployment-specific addresses (set per environment; may be undefined).
 * The EIP-2771 forwarder for the explorer's gasless writes is distinct from
 * the EduStack `EduForwarder` in the canonical table — set this only when
 * the env is wired. */
export const PROJECT_ADDRESSES: {
  /** EIP-2771 forwarder used for gasless writes (S-5). */
  forwarder?: Address;
} = {
  forwarder: process.env.NEXT_PUBLIC_FORWARDER_ADDRESS as Address | undefined,
};

/**
 * Genesis SALT allocations for chain 40204, GENERATED by `pnpm sync-addresses`
 * from citrate-chain `core/economics/src/genesis.rs` (`GenesisConfig::testnet_beta`)
 * into `src/generated/chainConstants.json`; labels from `scripts/lib/chainLabels.mjs`.
 * SALT is the NATIVE token (no ERC-20 Transfer events to index), so these known
 * genesis holders are the honest answer to "who holds the most SALT"; the agent
 * reads their live balances and says so. Verify with `eth_getBalance`.
 */
export const GENESIS_ALLOCATIONS: ReadonlyArray<{
  address: Address;
  label: string;
  genesisSalt: string;
}> = chainConstants.genesisAllocations as ReadonlyArray<{ address: Address; label: string; genesisSalt: string }>;

/**
 * Known Citrate system / AI-native contracts for labeling addresses in
 * forensic reads. Built once at module load by inverting the canonical
 * `contracts` + `aaStack` maps so a chain re-roll updates the labels with
 * no source edit. Keys are lowercased. Always confirm code with
 * `eth_getCode` before relying on a label.
 */
export const KNOWN_CONTRACTS: Readonly<Record<string, string>> = (() => {
  const out: Record<string, string> = {};
  for (const [name, addr] of Object.entries(canonicalAddresses.contracts)) {
    out[(addr as string).toLowerCase()] = name;
  }
  for (const [name, addr] of Object.entries(canonicalAddresses.aaStack)) {
    out[(addr as string).toLowerCase()] = name;
  }
  return Object.freeze(out);
})();

/** Label a known address (genesis holder or system contract), else null. */
export function knownLabel(address: string): string | null {
  const a = address.toLowerCase();
  if (KNOWN_CONTRACTS[a]) return KNOWN_CONTRACTS[a];
  const g = GENESIS_ALLOCATIONS.find((x) => x.address.toLowerCase() === a);
  return g ? g.label : null;
}
