import type { Address } from "viem";
import canonicalAddresses from "@/generated/addresses.json";

/**
 * Vendored copy of the federation-canonical contract-address table for
 * chain 40204. Source-of-truth lives at
 * `citrate-chain/contracts/addresses/40204.json` and is regenerated by
 * `citrate-chain/scripts/ops/emit-address-table.sh` after every
 * post-redeploy ceremony. Sync via `pnpm sync-addresses` (see
 * `scripts/sync-addresses.mjs`). Never hardcode a contract address inline;
 * read it from {@link CITRATE_ADDRESSES} or {@link CONTRACT_ADDRESSES}.
 */

/**
 * Well-known on-chain addresses CitrateScan decodes by default. Reads from
 * the vendored canonical, with `NEXT_PUBLIC_*` env overrides for preview /
 * staging deploys. Always confirm with `eth_getCode` before treating an
 * address as a contract (Rule 11).
 */
export const CITRATE_ADDRESSES = {
  /** AI ModelRegistry — see canonical contracts.ModelRegistry. */
  modelRegistry: (process.env.NEXT_PUBLIC_MODEL_REGISTRY ??
    canonicalAddresses.contracts.ModelRegistry) as Address,
  /** InferenceRouter — see canonical contracts.InferenceRouter. */
  inferenceRouter: (process.env.NEXT_PUBLIC_INFERENCE_ROUTER ??
    canonicalAddresses.contracts.InferenceRouter) as Address,
} as const;

/** The full contract map from the canonical table (for callers that need more
 * than the two top-of-mind ones above). Address is lowercased. */
export const CONTRACT_ADDRESSES = canonicalAddresses.contracts as Readonly<
  Record<string, Address>
>;

/** The ERC-4337 v0.7 AA stack from the canonical table. */
export const AA_STACK = canonicalAddresses.aaStack as Readonly<
  Record<string, Address>
>;

/** Deployment-specific addresses (set per environment; may be undefined).
 * The EIP-2771 forwarder for the explorer's gasless writes is distinct from
 * the EduStack `EduForwarder` in the canonical table — set this only when
 * the env is wired. */
export const PROJECT_ADDRESSES: {
  /** EIP-2771 forwarder used for gasless writes (S-5). */
  forwarder?: Address;
} = {
  forwarder: process.env.NEXT_PUBLIC_FORWARDER_ADDRESS as Address | undefined,
};

/**
 * Genesis SALT allocations (from citrate-chain `DEPLOYED_ADDRESSES.md`). SALT is
 * the NATIVE token — there are no ERC-20 Transfer events to index — so a full
 * "top holders" leaderboard needs a balance indexer. These known genesis holders
 * are the honest answer to "who holds the most SALT"; the agent reads their live
 * balances and says so. Verify with `eth_getBalance`.
 */
export const GENESIS_ALLOCATIONS: ReadonlyArray<{
  address: Address;
  label: string;
  genesisSalt: string;
}> = [
  { address: "0xaceaa7d00c024d32e6e0a07094ceb1a7706786d1", label: "Genesis treasury / mint authority", genesisSalt: "500000000" },
  { address: "0xf4adb1734f7bd9f8979bd53b2bf6d7690d562b6d", label: "Reserve", genesisSalt: "50000000" },
  { address: "0x4250675f9015e65fc866f3a373f82bb9dfc000c6", label: "Deployer EOA / coinbase", genesisSalt: "10000000" },
  { address: "0xb6e9a558a4f9dc9e3f667a3b446a48bddf671126", label: "Reserve", genesisSalt: "10000000" },
  { address: "0x6680b43af09d9b351332bf5378eb580e3b390182", label: "Testnet faucet", genesisSalt: "10000000" },
  { address: "0x04abae08ac643b2c518f22e212a27f7b6e14b4c3", label: "Reserve", genesisSalt: "5000000" },
];

/**
 * Known Citrate system / AI-native contracts for labeling addresses in
 * forensic reads. Built once at module load by inverting the canonical
 * `contracts` + `aaStack` maps so a chain re-roll updates the labels with
 * no source edit. Keys are lowercased. Always confirm code with
 * `eth_getCode` before relying on a label.
 */
export const KNOWN_CONTRACTS: Readonly<Record<string, string>> = (() => {
  const out: Record<string, string> = {};
  for (const [name, addr] of Object.entries(canonicalAddresses.contracts)) {
    out[(addr as string).toLowerCase()] = name;
  }
  for (const [name, addr] of Object.entries(canonicalAddresses.aaStack)) {
    out[(addr as string).toLowerCase()] = name;
  }
  return Object.freeze(out);
})();

/** Label a known address (genesis holder or system contract), else null. */
export function knownLabel(address: string): string | null {
  const a = address.toLowerCase();
  if (KNOWN_CONTRACTS[a]) return KNOWN_CONTRACTS[a];
  const g = GENESIS_ALLOCATIONS.find((x) => x.address.toLowerCase() === a);
  return g ? g.label : null;
}
