// The 40204 chain constants the explorer used to hand-copy (genesis SALT allocations and the
// precompile catalog) are generated by `pnpm sync-addresses` from citrate-chain inputs: the address
// book, `core/execution/src/precompiles/mod.rs` and `core/economics/src/genesis.rs`. These tests pin
// the parsers on small inline sources, the fail-closed rules, and that the app reads the generated file.
import { describe, it, expect, vi, afterEach } from "vitest";
import {
  parsePrecompileTables,
  parseGenesisAllocations,
  buildChainConstants,
  serializeChainConstants,
} from "../../../scripts/lib/chainSync.mjs";
import generated from "@/generated/chainConstants.json";
import { GENESIS_ALLOCATIONS } from "./addresses";
import { PRECOMPILES, describeContract, CITRATE_OVERVIEW } from "./contractCatalog";

const MOD_RS = `
pub const PURE_PRECOMPILE_ADDRESSES: [[u8; 20]; 2] = [
    verify::addresses::TENSOR_COMMIT,          // 0x0107
    commd_fold_verify::FOLD_COMMD_VERIFY,      // 0x0130 (feature-gated verifier)
];

/// docs
pub const AGENT_FORK_PRECOMPILE_ADDRESSES: [[u8; 20]; 2] = [
    lora::LORA_APPLY,                    // 0x0112
    agent_ops::AGENT_OPS,                // 0x0122
];
`;

const GENESIS_RS = `
pub const TESTNET_TREASURY_ADDRESS: Address = Address([
    0xa5, 0xd0, 0x97, 0xc0, 0xab, 0xbb, 0x3b, 0x6b, 0xbd, 0xb7,
    0x5b, 0xd0, 0x6d, 0x51, 0xb4, 0x4f, 0x92, 0x77, 0xe6, 0xd4,
]);
pub const TESTNET_ECOSYSTEM_ADDRESS: Address = Address([0x22; 20]);
pub const VALIDATOR_STAKER_1_ADDRESS: Address = Address([
    0xb4, 0xe4, 0x27, 0x31, 0x90, 0x8a, 0x00, 0xfe, 0xa7, 0xe1,
    0xae, 0xdb, 0x08, 0x17, 0xe7, 0x8b, 0x41, 0x68, 0x89, 0xc5,
]);
pub const VALIDATOR_STAKER_GENESIS_SALT: u64 = 40_000_000;
impl GenesisConfig {
    pub fn devnet() -> Self {
        Self { accounts: vec![account(TESTNET_ECOSYSTEM_ADDRESS, 1)] }
    }
    pub fn testnet_beta() -> Self {
        Self {
            chain_id: 40204,
            accounts: vec![
                // Treasury (500B SALT)
                account(TESTNET_TREASURY_ADDRESS, 500_000_000_000),
                account(VALIDATOR_STAKER_1_ADDRESS, VALIDATOR_STAKER_GENESIS_SALT),
                arachnid_deterministic_deployer_account(),
            ],
        }
    }
    pub fn team() -> Self { todo() }
}
`;

const BOOK = {
  chainId: 40204,
  precompiles: {
    ModelDeploy: "0x0000000000000000000000000000000000000100",
    TensorCommit: "0x0000000000000000000000000000000000000107",
  },
};
const DESCRIPTIONS = {
  ModelDeploy: "deploy",
  TensorCommit: "commit",
  FoldCommdVerify: "fold",
  LoraApply: "lora apply",
  AgentOps: "agent ops",
};
const LABELS = { TESTNET_TREASURY_ADDRESS: "Genesis treasury", VALIDATOR_STAKER_1_ADDRESS: "Validator staker 1" };
const addr = (short: string) => `0x${short.padStart(40, "0")}`;

describe("parsePrecompileTables", () => {
  it("reads both chain tables, address from the trailing comment, name from the element", () => {
    expect(parsePrecompileTables(MOD_RS)).toEqual([
      { address: addr("0107"), constName: "TENSOR_COMMIT", table: "pure" },
      { address: addr("0130"), constName: "FOLD_COMMD_VERIFY", table: "pure" },
      { address: addr("0112"), constName: "LORA_APPLY", table: "agent" },
      { address: addr("0122"), constName: "AGENT_OPS", table: "agent" },
    ]);
  });

  it("fails when a table is missing or its length disagrees with the declared size", () => {
    expect(() => parsePrecompileTables(MOD_RS.replace("AGENT_FORK_PRECOMPILE_ADDRESSES", "OTHER"))).toThrow(/AGENT_FORK_PRECOMPILE_ADDRESSES/);
    expect(() => parsePrecompileTables(MOD_RS.replace("[[u8; 20]; 2] = [\n    verify", "[[u8; 20]; 3] = [\n    verify"))).toThrow(/declares 3/);
  });
});

describe("parseGenesisAllocations", () => {
  it("reads testnet_beta's accounts, resolving byte-array addresses and u64 constants", () => {
    expect(parseGenesisAllocations(GENESIS_RS)).toEqual([
      { constName: "TESTNET_TREASURY_ADDRESS", address: "0xa5d097c0abbb3b6bbdb75bd06d51b44f9277e6d4", genesisSalt: "500000000000" },
      { constName: "VALIDATOR_STAKER_1_ADDRESS", address: "0xb4e42731908a00fea7e1aedb0817e78b416889c5", genesisSalt: "40000000" },
    ]);
  });

  it("fails when testnet_beta is missing or a constant cannot be resolved", () => {
    expect(() => parseGenesisAllocations(GENESIS_RS.replace("fn testnet_beta", "fn other"))).toThrow(/testnet_beta/);
    expect(() => parseGenesisAllocations(GENESIS_RS.replace("pub const VALIDATOR_STAKER_GENESIS_SALT: u64 = 40_000_000;", ""))).toThrow(
      /VALIDATOR_STAKER_GENESIS_SALT/,
    );
  });
});

describe("buildChainConstants", () => {
  const inputs = { book: BOOK, precompileRs: MOD_RS, genesisRs: GENESIS_RS, descriptions: DESCRIPTIONS, genesisLabels: LABELS };

  it("merges book and chain precompiles by address, book names first, sorted", () => {
    const out = buildChainConstants(inputs);
    expect(out.precompiles).toEqual([
      { address: addr("0100"), name: "ModelDeploy", purpose: "deploy", sources: ["book"] },
      { address: addr("0107"), name: "TensorCommit", purpose: "commit", sources: ["book", "chain:pure"] },
      { address: addr("0112"), name: "LoraApply", purpose: "lora apply", sources: ["chain:agent"] },
      { address: addr("0122"), name: "AgentOps", purpose: "agent ops", sources: ["chain:agent"] },
      { address: addr("0130"), name: "FoldCommdVerify", purpose: "fold", sources: ["chain:pure"] },
    ]);
    expect(out.genesisAllocations).toEqual([
      { address: "0xa5d097c0abbb3b6bbdb75bd06d51b44f9277e6d4", label: "Genesis treasury", genesisSalt: "500000000000" },
      { address: "0xb4e42731908a00fea7e1aedb0817e78b416889c5", label: "Validator staker 1", genesisSalt: "40000000" },
    ]);
  });

  it("fails when a chain precompile has no catalog description", () => {
    const { AgentOps: _drop, ...rest } = DESCRIPTIONS;
    void _drop;
    expect(() => buildChainConstants({ ...inputs, descriptions: rest })).toThrow(/AgentOps \(0x0+122\)/);
  });

  it("fails when a genesis account has no label", () => {
    expect(() => buildChainConstants({ ...inputs, genesisLabels: { TESTNET_TREASURY_ADDRESS: "Genesis treasury" } })).toThrow(
      /VALIDATOR_STAKER_1_ADDRESS/,
    );
  });

  it("serializes deterministically, so --check can compare bytes", () => {
    const a = serializeChainConstants(buildChainConstants(inputs));
    expect(serializeChainConstants(buildChainConstants(inputs))).toBe(a);
    expect(a.endsWith("\n")).toBe(true);
  });
});

describe("the app reads the generated constants", () => {
  it("GENESIS_ALLOCATIONS is the generated list", () => {
    expect(GENESIS_ALLOCATIONS).toEqual(generated.genesisAllocations);
    expect(GENESIS_ALLOCATIONS.length).toBeGreaterThan(0);
  });

  it("PRECOMPILES covers every generated precompile, including the agent precompiles, and nothing else", () => {
    expect(Object.keys(PRECOMPILES).sort()).toEqual(generated.precompiles.map((p) => p.address).sort());
    for (const short of ["0112", "0113", "0121", "0122"]) expect(PRECOMPILES[addr(short)]).toBeTruthy();
    expect(PRECOMPILES[addr("1001")]).toBeUndefined();
    expect(describeContract(addr("0100")).name).toBe("ModelDeploy");
    expect(CITRATE_OVERVIEW).not.toMatch(/1000\/1001\/1003/);
  });
});

describe("model registry / inference router env overrides", () => {
  afterEach(() => {
    vi.unstubAllEnvs();
    vi.resetModules();
  });

  it("an empty or malformed override falls back to the vendored book", async () => {
    const book = (await import("@/generated/addresses.json")).default.contracts as Record<string, string>;
    vi.stubEnv("NEXT_PUBLIC_MODEL_REGISTRY", "");
    vi.stubEnv("NEXT_PUBLIC_INFERENCE_ROUTER", "not-an-address");
    vi.resetModules();
    const { CITRATE_ADDRESSES } = await import("./addresses");
    expect(CITRATE_ADDRESSES.modelRegistry).toBe(book.ModelRegistry);
    expect(CITRATE_ADDRESSES.inferenceRouter).toBe(book.InferenceRouter);
  });
});
